# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: MidtownTechnologyGroup.Detour
PackageVersion: 0.1.3
PackageLocale: en-US
Publisher: Midtown Technology Group LLC
PublisherUrl: https://midtowntg.com
PublisherSupportUrl: https://github.com/Midtown-Technology-Group/detour/issues
Author: Thomas Bray
PackageName: Detour
PackageUrl: https://github.com/Midtown-Technology-Group/detour
License: AGPL-3.0-only
LicenseUrl: https://github.com/Midtown-Technology-Group/detour/blob/main/LICENSE
Copyright: Copyright (c) 2026 Midtown Technology Group LLC
ShortDescription: Track the work you did to get back to the work you meant to do.
Description: |
  Track the work you did to get back to the work you meant to do.
Moniker: detour
Tags:
  - cli
  - productivity
  - midtown
ReleaseNotes: |
  Initial MSI release for Detour.
ReleaseNotesUrl: https://github.com/Midtown-Technology-Group/detour/releases/tag/v0.1.3
ManifestType: defaultLocale
ManifestVersion: 1.5.0
