# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: MidtownTechnologyGroup.MailTriage
PackageVersion: 0.1.0
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
UpgradeBehavior: install
ProductCode: '{9145C120-2C27-467C-8CB8-0902A0911DC9}'
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Midtown-Technology-Group/mail-triage/releases/download/v0.1.0/mail-triage.msi
    InstallerSha256: 3ed5aa3353b481da28069202c4a9bf5fd2cf115155680d7a0f49d025a4889bf0
    InstallerSwitches:
      Silent: /qn
      SilentWithProgress: /qb
ManifestType: installer
ManifestVersion: 1.5.0
