# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: MidtownTechnologyGroup.CalendarGlance
PackageVersion: 0.1.0
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
UpgradeBehavior: install
ProductCode: '{8420AC56-8F09-421D-92ED-C782D032572E}'
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Midtown-Technology-Group/calendar-glance/releases/download/v0.1.0/calendar-glance.msi
    InstallerSha256: d9a65768aaf299f2145b6646ebbb32340701dbfba9cb259147901abab3cfcf1f
    InstallerSwitches:
      Silent: /qn
      SilentWithProgress: /qb
ManifestType: installer
ManifestVersion: 1.5.0
