# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: MidtownTechnologyGroup.Halocli
PackageVersion: 1.12.0
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
UpgradeBehavior: install
ProductCode: '{4275C2B6-295A-4217-9A4D-2C1CC9BED802}'
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Midtown-Technology-Group/halocli/releases/download/v1.12.0/halocli.msi
    InstallerSha256: cb6103c57e35aba4823efbef4a2828e425a3f67eb38ee0e3718334bea5115833
    InstallerSwitches:
      Silent: /qn
      SilentWithProgress: /qb
ManifestType: installer
ManifestVersion: 1.5.0
