# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: MidtownTechnologyGroup.Halocli
PackageVersion: 1.14.0
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
UpgradeBehavior: install
ProductCode: '{532A311E-6BD5-4394-8FFD-1492963AA035}'
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Midtown-Technology-Group/halocli/releases/download/v1.14.0/halocli.msi
    InstallerSha256: 0ad53bf98f35663ce72ae6b110d1df86285bcccd7c06cb4a57dbb02f475d1258
    InstallerSwitches:
      Silent: /qn
      SilentWithProgress: /qb
ManifestType: installer
ManifestVersion: 1.5.0
