# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: MidtownTechnologyGroup.Halocli
PackageVersion: 1.8.0
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
UpgradeBehavior: install
ProductCode: '{08AB4A7E-AEE9-493B-A676-72AC1CF674B2}'
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Midtown-Technology-Group/halocli/releases/download/v1.8.0/halocli.msi
    InstallerSha256: c0a4c16158feaa77cdf84ff5b1fd3f9b204f3629d14a255d9fae3ab279f57a55
    InstallerSwitches:
      Silent: /qn
      SilentWithProgress: /qb
ManifestType: installer
ManifestVersion: 1.5.0
